version: "3.9"
services:
  axonserver:
    image: axoniq/axonserver:latest-dev
    ports:
      - 8024:8024
      - 8124:8124
    volumes:
      - ./.data/axonserver/data:/axonserver/data
      - ./.data/axonserver/events:/axonserver/events
      - ./.data/axonserver/plugins:/axonserver/plugins
